apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitWebhook
metadata:
  name: {{ include "quarkus-pipeline.fullname" . }}
  labels:
    {{- include "quarkus-pipeline.labels" . | nindent 4 }}  
spec:
  gitHub:
    gitServerCredentials:
      name: github-credentials
  repositoryOwner: {{ .Values.repositoryOwner }}
  ownerType:  {{ .Values.ownerType }}
  repositoryName: {{ .Values.repositoryName }}
  webhookURL: https://{{ include "quarkus-pipeline.fullname" . }}-{{ .Release.Namespace}}.{{ .Values.baseURL }}
  insecureSSL: true
  webhookSecret:
    name: {{ include "quarkus-pipeline.fullname" . }}-webhook
  events:
    - push  
  content: json
  active: true  