apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "quarkus-pipeline.fullname" . }}-webhook
  labels:
    {{- include "quarkus-pipeline.labels" . | nindent 4 }}  
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: {{ .Release.Namespace }}-kv
      name: webhook_secret
      path: {{ .Values.team }}/{{ .Release.Namespace }}-kv/{{ include "quarkus-pipeline.fullname" . }}-webhook
  output:
    name: {{ include "quarkus-pipeline.fullname" . }}-webhook
    stringData:
      secret: '{{ "{{" }} .webhook_secret {{ "}}" }}'
    type: Opaque